name: "Deploy to NuGet"

on:
  push:
    tags:
      - 'v*'

env:
  PROJECT_PATH: 'SendGridAzFunction/Jodelac.SendGridAzFunction.csproj'
  PACKAGE_OUTPUT_DIR: ${{ github.workspace }}/output
  NUGET_SRC_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy:
    name: 'Deploy'  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.x
      
      - name: 'Restore dependencies'
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build with dotnet
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release 

      - name: 'Get Version'
        id: version
        uses: battila7/get-version-action@v2

      - name: Push NuGet package  
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --output ${{ env.PACKAGE_OUTPUT_DIR }} -p:PackageVersion=${{ steps.version.outputs.version-without-v }} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg

      - name: 'Push Package'
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIR }}/*.nupkg --source ${{ env.NUGET_SRC_URL }} -k ${{ secrets.NUGETAPIKEY }} -ss  ${{ env.PACKAGE_OUTPUT_DIR }}/*.snupkg
